//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompleteLibrary_Project.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompleteLibrary_Project.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This loan has been successfully returned!.
        /// </summary>
        internal static string _return {
            get {
                return ResourceManager.GetString("return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Media.
        /// </summary>
        internal static string add_media {
            get {
                return ResourceManager.GetString("add_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age restriction.
        /// </summary>
        internal static string age_restriction {
            get {
                return ResourceManager.GetString("age_restriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiobook.
        /// </summary>
        internal static string audiobook {
            get {
                return ResourceManager.GetString("audiobook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string book {
            get {
                return ResourceManager.GetString("book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        internal static string borrow {
            get {
                return ResourceManager.GetString("borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout one of these items.
        /// </summary>
        internal static string checkout_item {
            get {
                return ResourceManager.GetString("checkout_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given birthdate is invalid!.
        /// </summary>
        internal static string date_error {
            get {
                return ResourceManager.GetString("date_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string director {
            get {
                return ResourceManager.GetString("director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB (yyyy/mm/dd):.
        /// </summary>
        internal static string dob {
            get {
                return ResourceManager.GetString("dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string edition {
            get {
                return ResourceManager.GetString("edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ID Number:.
        /// </summary>
        internal static string enter_id {
            get {
                return ResourceManager.GetString("enter_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name(s):.
        /// </summary>
        internal static string fname {
            get {
                return ResourceManager.GetString("fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Hold.
        /// </summary>
        internal static string hold {
            get {
                return ResourceManager.GetString("hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an invalid ID!.
        /// </summary>
        internal static string id_error {
            get {
                return ResourceManager.GetString("id_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrator.
        /// </summary>
        internal static string illustrator {
            get {
                return ResourceManager.GetString("illustrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: the following fields must be integers:
        ///publication year, age restriction, duration,
        ///and edition.
        /// </summary>
        internal static string int_error {
            get {
                return ResourceManager.GetString("int_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This loan does not exist..
        /// </summary>
        internal static string invalid_loan {
            get {
                return ResourceManager.GetString("invalid_loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language1 {
            get {
                return ResourceManager.GetString("language1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarian.
        /// </summary>
        internal static string librarian {
            get {
                return ResourceManager.GetString("librarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new librarian has been added!
        ///Their ID is {0}..
        /// </summary>
        internal static string librarian_add {
            get {
                return ResourceManager.GetString("librarian_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarians.
        /// </summary>
        internal static string librarians {
            get {
                return ResourceManager.GetString("librarians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name(s):.
        /// </summary>
        internal static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine.
        /// </summary>
        internal static string magazine {
            get {
                return ResourceManager.GetString("magazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media ID:.
        /// </summary>
        internal static string media_id {
            get {
                return ResourceManager.GetString("media_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new item has been added to
        ///your library! Its new id is {0}..
        /// </summary>
        internal static string media_insert {
            get {
                return ResourceManager.GetString("media_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Media Type.
        /// </summary>
        internal static string media_selection {
            get {
                return ResourceManager.GetString("media_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string member {
            get {
                return ResourceManager.GetString("member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new member has been added!
        ///Their ID is {0}..
        /// </summary>
        internal static string member_add {
            get {
                return ResourceManager.GetString("member_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string movie {
            get {
                return ResourceManager.GetString("movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrator.
        /// </summary>
        internal static string narrator {
            get {
                return ResourceManager.GetString("narrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Your search has not yielded any results. Make sure your title is spelt correctly and the correct type is selected..
        /// </summary>
        internal static string null_search {
            get {
                return ResourceManager.GetString("null_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication month.
        /// </summary>
        internal static string publication_month {
            get {
                return ResourceManager.GetString("publication_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication year.
        /// </summary>
        internal static string publication_year {
            get {
                return ResourceManager.GetString("publication_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string publisher {
            get {
                return ResourceManager.GetString("publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Item.
        /// </summary>
        internal static string return_item {
            get {
                return ResourceManager.GetString("return_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a book, movie, audiobook, or magazine within the library!.
        /// </summary>
        internal static string search_message {
            get {
                return ResourceManager.GetString("search_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the following....
        /// </summary>
        internal static string select_following {
            get {
                return ResourceManager.GetString("select_following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have now checked out {0}!
        ///You have this item for {1} days..
        /// </summary>
        internal static string successful_checkout {
            get {
                return ResourceManager.GetString("successful_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have now placed {0} on hold!.
        /// </summary>
        internal static string successful_hold {
            get {
                return ResourceManager.GetString("successful_hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are too young to borrow this item..
        /// </summary>
        internal static string too_young_exception {
            get {
                return ResourceManager.GetString("too_young_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is unavailable to you for checkout..
        /// </summary>
        internal static string unsuccessful_checkout {
            get {
                return ResourceManager.GetString("unsuccessful_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be put on hold because it is already available
        ///or because you already have place it on hold..
        /// </summary>
        internal static string unsuccessful_hold {
            get {
                return ResourceManager.GetString("unsuccessful_hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID:.
        /// </summary>
        internal static string user_id {
            get {
                return ResourceManager.GetString("user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Complete Library!.
        /// </summary>
        internal static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
    }
}
